### ISSUE TITLE
State management - reset & initialize

### ISSUE THREAD

**Issue by eliottvincent** [makers-for-life/makair#158]
Implementing the state management of the whole system (i.e. blower, valves, alarms, etc.) could be great.
Methods:
- reset --> clear the state and all its variables
- initialize --> set variables to their default values

This would allow us to start from a clean state and avoid being in a weird state.
Please close if this is already implemented.

**Comment by dsferruzza** [comment]
I believe this is already done, but maybe we should discuss this in more details to make sure our visions are aligned
