### ISSUE TITLE
Ventilation Specifications

### ISSUE THREAD

**Issue by simonsan** [makers-for-life/makair#49]
Some information on `Ventilation Specifications`:

From the Clinical Guidance this document summarizes the minimum set of requirements for ventilation:
https://e-vent.mit.edu/clinical/key-ventilation-specifications/

Also some more engineering specifications from the University of Florida:
https://simulation.health.ufl.edu/technology-development/open-source-ventilator-project/

One thing to keep in mind as well, that could be solved in the early design stages:

"The American Society of Anesthesiologists issued [guidance](https://www.asahq.org/about-asa/governance-and-committees/asa-committees/committee-on-occupational-health/coronavirus) on Feb. 23 discouraging CPAP use in COVID-19 patients — advice largely informed by experience with the SARS epidemic in 2003. Studies dating to 2003 suggest that such devices can pump viruses into the air, potentially increasing the spread of a contagious disease.

During the SARS outbreak in Toronto, half of all SARS cases, including three deaths, occurred among health care workers. Some of the greatest risk arose when doctors and nurses were exposed to aerosolized virus through the use of positive airway pressure machines or other respiratory therapy devices." ([Source](https://www.npr.org/sections/health-shots/2020/03/27/822211604/cpap-machines-were-seen-as-ventilator-alternatives-but-could-spread-covid-19?t=1585487737279))

**Comment by eliottvincent** [comment]
Thanks a lot for the documentation, and the concerns about virus rejection in the room's air. We already have measures in place to lower the risk of aerosolized virus (multiple filters).
