### ISSUE TITLE
Add a licence to each source file

### ISSUE THREAD

**Issue by Mefl** [makers-for-life/makair#50]

**Comment by jlbirccyn** [comment]
Done with e412d7a465cec8bb79fc1c047b9ccc1bf323c1b0

**Comment by dsferruzza** [comment]
I'm reopening this because:

1. Headers are not in the current version
2. I believe we did not actually choose a specific license yet? (cc @valeriansaliou )

**Comment by valeriansaliou** [comment]
The current general license is the following one: https://github.com/covid-response-projects/covid-respirator/blob/master/LICENSE.md

Question is as follows: do we accept commercial use of our project? If we want industrials to be able to mass produce our respirator, this should probably be allowed, as long as changes on our CAD models, software code, and more are re-licensed as OSS / same license.
